export class Menu {
  constructor(public id: number,
              public title: string,
              public routerLink: string,
              public href: string,
              public icon: string,
              public target: string,
              public hasSubMenu: boolean,
              public parentId: number) { }
}


export let verticalMenuItems: Menu[];
verticalMenuItems = [
  new Menu(1, 'Dashboard', '/', '', 'dashboard', '', false, 0),
  new Menu(2, 'Users', '/users', '', 'supervisor_account', '', false, 0),
  new Menu(3, 'UI Features', '', '', 'computer', '', true, 0),
  new Menu(4, 'Buttons', '/ui/buttons', '', 'keyboard', '', false, 3),
  new Menu(5, 'Cards', '/ui/cards', '', 'card_membership', '', false, 3),
  new Menu(6, 'Lists', '/ui/lists', '', 'list', '', false, 3),
  new Menu(7, 'Grids', '/ui/grids', '', 'grid_on', '', false, 3),
  new Menu(8, 'Tabs', '/ui/tabs', '', 'tab', '', false, 3),
  new Menu(9, 'Expansion Panel', '/ui/expansion-panel', '', 'dns', '', false, 3),
  new Menu(10, 'Chips', '/ui/chips', '', 'label', '', false, 3),
  new Menu(11, 'Progress', '/ui/progress', '', 'data_usage', '', false, 3),
  new Menu(12, 'Dialog', '/ui/dialog', '', 'open_in_new', '', false, 3),
  new Menu(13, 'Tooltip', '/ui/tooltip', '', 'chat_bubble', '', false, 3),
  new Menu(14, 'Snackbar', '/ui/snack-bar', '', 'sms', '', false, 3),
  new Menu(15, 'Dynamic Menu', '/dynamic-menu', '', 'format_list_bulleted', '', false, 0),
  new Menu(16, 'Mailbox', '/mailbox', '', 'email', '', false, 0),
  new Menu(17, 'Chat', '/chat', '', 'chat', '', false, 0),
  new Menu(20, 'Form Controls', '', '', 'dvr', '', true, 0),
  new Menu(21, 'Autocomplete', '/form-controls/autocomplete', '', 'short_text', '', false, 20),
  new Menu(22, 'Checkbox', '/form-controls/checkbox', '', 'check_box', '', false, 20),
  new Menu(23, 'Datepicker', '/form-controls/datepicker', '', 'today', '', false, 20),
  new Menu(24, 'Form field', '/form-controls/form-field', '', 'view_stream', '', false, 20),
  new Menu(25, 'Input', '/form-controls/input', '', 'input', '', false, 20),
  new Menu(26, 'Radio button', '/form-controls/radio-button', '', 'radio_button_checked', '', false, 20),
  new Menu(27, 'Select', '/form-controls/select', '', 'playlist_add_check', '', false, 20),
  new Menu(28, 'Slider', '/form-controls/slider', '', 'tune', '', false, 20),
  new Menu(29, 'Slide toggle', '/form-controls/slide-toggle', '', 'star_half', '', false, 20),
  new Menu(30, 'Tables', '', '', 'view_module', '', true, 0),
  new Menu(31, 'Basic', '/tables/basic', '', 'view_column', '', false, 30),
  new Menu(32, 'Paging', '/tables/paging', '', 'last_page', '', false, 30),
  new Menu(33, 'Sorting', '/tables/sorting', '', 'sort', '', false, 30),
  new Menu(34, 'Filtering', '/tables/filtering', '', 'format_line_spacing', '', false, 30),
  new Menu(35, 'Selecting', '/tables/selecting', '', 'playlist_add_check', '', false, 30),
  new Menu(36, 'NGX DataTable', '/tables/ngx-table', '', 'view_array', '', false, 30),
  new Menu(40, 'Pages', '', '', 'library_books', '', true, 0),
  new Menu(43, 'Login', '/login', '', 'exit_to_app', '', false, 40),
  new Menu(44, 'Register', '/register', '', 'person_add', '', false, 40),
  new Menu(45, 'Blank', '/blank', '', 'check_box_outline_blank', '', false, 40),
  new Menu(46, 'Page Not Found', '/pagenotfound', '', 'error_outline', '', false, 40),
  new Menu(47, 'Error', '/error', '', 'warning', '', false, 40),
  new Menu(48, 'Landing', '/landing', '', 'filter', '', false, 40),
  new Menu(49, 'Profile', '', '', 'person', '', true, 40),
  new Menu(50, 'Projects', '/profile/projects', '', 'note', '', false, 49),
  new Menu(51, 'User Info', '/profile/user-info', '', 'perm_contact_calendar', '', false, 49),
  new Menu(55, 'Schedule', '/schedule', '', 'event', '', false, 0),
  new Menu(66, 'Maps', '', '', 'map', '', true, 0),
  new Menu(67, 'Google Maps', '/maps/googlemaps', '', 'location_on', '', false, 66),
  new Menu(68, 'Leaflet Maps', '/maps/leafletmaps', '', 'my_location', '', false, 66),
  new Menu(70, 'Charts', '', '', 'multiline_chart', '', true, 0),
  new Menu(71, 'Bar Charts', '/charts/bar', '', 'insert_chart', '', false, 70),
  new Menu(72, 'Pie Charts', '/charts/pie', '', 'pie_chart', '', false, 70),
  new Menu(73, 'Line Charts', '/charts/line', '', 'show_chart', '', false, 70),
  new Menu(74, 'Bubble Charts', '/charts/bubble', '', 'bubble_chart', '', false, 70),
  new Menu(81, 'Drag & Drop', '/drag-drop', '', 'mouse', '', false, 0),
  new Menu(85, 'Material Icons', '/icons', '', 'insert_emoticon', '', false, 0),
  new Menu(140, 'Level 1', '', '', 'more_horiz', '', true, 0),
  new Menu(141, 'Level 2', '', '', 'folder_open', '', true, 140),
  new Menu(142, 'Level 3', '', '', 'folder_open', '', true, 141),
  new Menu(143, 'Level 4', '', '', 'folder_open', '', true, 142),
  new Menu(144, 'Level 5', '', 'http://themeseason.com', 'link', '', false, 143),
  new Menu(200, 'External Link', '', 'http://themeseason.com', 'open_in_new', '_blank', false, 0)
];

export const horizontalMenuItems = [
  new Menu(1, 'Dashboard', '/', '', 'dashboard', '', false, 0),
  new Menu(2, 'Users', '/users', '', 'supervisor_account', '', false, 0),
  new Menu(3, 'UI Features', '', '', 'computer', '', true, 0),
  new Menu(4, 'Buttons', '/ui/buttons', '', 'keyboard', '', false, 3),
  new Menu(5, 'Cards', '/ui/cards', '', 'card_membership', '', false, 3),
  new Menu(6, 'Lists', '/ui/lists', '', 'list', '', false, 3),
  new Menu(7, 'Grids', '/ui/grids', '', 'grid_on', '', false, 3),
  new Menu(8, 'Tabs', '/ui/tabs', '', 'tab', '', false, 3),
  new Menu(9, 'Expansion Panel', '/ui/expansion-panel', '', 'dns', '', false, 3),
  new Menu(10, 'Chips', '/ui/chips', '', 'label', '', false, 3),
  new Menu(11, 'Progress', '/ui/progress', '', 'data_usage', '', false, 3),
  new Menu(12, 'Dialog', '/ui/dialog', '', 'open_in_new', '', false, 3),
  new Menu(13, 'Tooltip', '/ui/tooltip', '', 'chat_bubble', '', false, 3),
  new Menu(14, 'Snackbar', '/ui/snack-bar', '', 'sms', '', false, 3),
  new Menu(16, 'Mailbox', '/mailbox', '', 'email', '', false, 40),
  new Menu(17, 'Chat', '/chat', '', 'chat', '', false, 40),
  new Menu(20, 'Form Controls', '', '', 'dvr', '', true, 0),
  new Menu(21, 'Autocomplete', '/form-controls/autocomplete', '', 'short_text', '', false, 20),
  new Menu(22, 'Checkbox', '/form-controls/checkbox', '', 'check_box', '', false, 20),
  new Menu(23, 'Datepicker', '/form-controls/datepicker', '', 'today', '', false, 20),
  new Menu(24, 'Form field', '/form-controls/form-field', '', 'view_stream', '', false, 20),
  new Menu(25, 'Input', '/form-controls/input', '', 'input', '', false, 20),
  new Menu(26, 'Radio button', '/form-controls/radio-button', '', 'radio_button_checked', '', false, 20),
  new Menu(27, 'Select', '/form-controls/select', '', 'playlist_add_check', '', false, 20),
  new Menu(28, 'Slider', '/form-controls/slider', '', 'tune', '', false, 20),
  new Menu(29, 'Slide toggle', '/form-controls/slide-toggle', '', 'star_half', '', false, 20),
  new Menu(30, 'Tables', '', '', 'view_module', '', true, 0),
  new Menu(31, 'Basic', '/tables/basic', '', 'view_column', '', false, 30),
  new Menu(32, 'Paging', '/tables/paging', '', 'last_page', '', false, 30),
  new Menu(33, 'Sorting', '/tables/sorting', '', 'sort', '', false, 30),
  new Menu(34, 'Filtering', '/tables/filtering', '', 'format_line_spacing', '', false, 30),
  new Menu(35, 'Selecting', '/tables/selecting', '', 'playlist_add_check', '', false, 30),
  new Menu(36, 'NGX DataTable', '/tables/ngx-table', '', 'view_array', '', false, 30),
  new Menu(70, 'Charts', '', '', 'multiline_chart', '', true, 0),
  new Menu(71, 'Bar Charts', '/charts/bar', '', 'insert_chart', '', false, 70),
  new Menu(72, 'Pie Charts', '/charts/pie', '', 'pie_chart', '', false, 70),
  new Menu(73, 'Line Charts', '/charts/line', '', 'show_chart', '', false, 70),
  new Menu(74, 'Bubble Charts', '/charts/bubble', '', 'bubble_chart', '', false, 70),
  new Menu(66, 'Maps', '', '', 'map', '', true, 70),
  new Menu(67, 'Google Maps', '/maps/googlemaps', '', 'location_on', '', false, 66),
  new Menu(68, 'Leaflet Maps', '/maps/leafletmaps', '', 'my_location', '', false, 66),
  new Menu(81, 'Drag & Drop', '/drag-drop', '', 'mouse', '', false, 3),
  new Menu(85, 'Material Icons', '/icons', '', 'insert_emoticon', '', false, 3),
  new Menu(40, 'Pages', '', '', 'library_books', '', true, 0),
  new Menu(43, 'Login', '/login', '', 'exit_to_app', '', false, 40),
  new Menu(44, 'Register', '/register', '', 'person_add', '', false, 40),
  new Menu(45, 'Blank', '/blank', '', 'check_box_outline_blank', '', false, 40),
  new Menu(46, 'Page Not Found', '/pagenotfound', '', 'error_outline', '', false, 40),
  new Menu(47, 'Error', '/error', '', 'warning', '', false, 40),
  new Menu(48, 'Landing', '/landing', '', 'filter', '', false, 40),
  new Menu(49, 'Profile', '', '', 'person', '', true, 40),
  new Menu(50, 'Projects', '/profile/projects', '', 'note', '', false, 49),
  new Menu(51, 'User Info', '/profile/user-info', '', 'perm_contact_calendar', '', false, 49),
  new Menu(55, 'Schedule', '/schedule', '', 'event', '', false, 40),
  new Menu(200, 'External Link', '', 'http://themeseason.com', 'open_in_new', '_blank', false, 40)
]
